### ISSUE TITLE
Users can only join/leave the first course created.

### ISSUE THREAD

**Issue by elGatoMantocko** [cjsauer/study-snap#11]
Any course created after the first one can't be joined or left as far as I can tell. I also noticed that after a user joins one course, they will be joined on other courses as well.

**Comment by cjsauer** [comment]
Any errors in the console?

**Comment by elGatoMantocko** [comment]
Doesn't look like there are any console errors.

**Comment by cjsauer** [comment]
I just noticed this line in the permissions file:

``` javascript
update: function(userId, doc, fields, modifier) {
  return false;
},
```

I bet it's a permission issue since updates are forbidden at the moment. We'll need to check the user is in the right role (like the insert permission) and then also check to see that we're only modifying the `students` field in the fields parameter.

**Comment by elGatoMantocko** [comment]
Sounds good. I will try to look at it today.

**Comment by cjsauer** [comment]
Very strange that there are no errors though. In the least, Meteor should throw an access denied error, so I'm wondering if there might be one more hidden issue.

**Comment by cjsauer** [comment]
Ah I just remember that server code is immune to those permission rules, they only apply when the client tries to modify the collection directly.

**Comment by elGatoMantocko** [comment]
[this may point us in the right direction](http://stackoverflow.com/questions/14462962/meteor-mongodb-error-cannot-apply-addtoset-modifier-to-non-array). I am looking into it now

**Comment by elGatoMantocko** [comment]
I just did some more deliberate testing, and I can confirm that this isn't a database issue. The users are correctly being added to the mongo collection. The button just isn't flipping to the "Leave course" button.

Edit: This also means that there may be an issue in how the leaderboard is displayed. Because the students aren't appearing on it when they join.

Edit no. 2: It seems like the status of the button is being maintained by the first courses join status to a particular user.

Example case: An admin creates 3 courses and joins the second two. The database correctly maintains that the user is in the second two, but the button reflects that they have joined neither. The user joins the first course and the buttons now reflect the status of the first course. The user leaves all 3 courses (now that the "leave" button has appeared). Mongo will now reflect that the user is no longer a member of any of the courses.

**Comment by elGatoMantocko** [comment]
Just pushed new changes to [leaderboard](https://github.com/cjsauer/study-snap/tree/leaderboard) should fix the issues that I have been experiencing.

**Comment by elGatoMantocko** [comment]
Closing for PR #12
