### ISSUE TITLE
URL path is not rendering correctly

### ISSUE THREAD

**Issue by elGatoMantocko** [cjsauer/study-snap#4]
## Criticality: High

I created a course and then attempted to navigate to the URL where it should have been located, but 'undefined' is being rendered in front of the :_id property. 

This goes back to the top of develop. Not sure how much further back after that though.

![screen shot 2015-06-02 at 10 37 05 am](https://cloud.githubusercontent.com/assets/6691665/7938408/54fa4450-0913-11e5-95e9-b95c5cad68cd.png)

**Comment by cjsauer** [comment]
Did you navigate to it through the search drop down?

**Comment by elGatoMantocko** [comment]
Yes

**Comment by cjsauer** [comment]
I can't seem to reproduce this. I've followed these steps:
1. Click create new course
2. Fill out the form correctly with a unique deck id
3. Input enough of the school name into the search box to find the new course
4. Click on the course link

It's possible your database was out of sync in some way.

**Comment by elGatoMantocko** [comment]
Just tested it again. It worked. I swear I'm not going crazy.

I bet you are right that mongo was out of sync or something along those lines. It's weird though because I drop the database every time with the `Courses.remove({});` line in there.

That image was taken 2 hours ago on the same branch and same computer.
